# permissions for end users to view morpheuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: morpheus-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: morpheus-operator
    app.kubernetes.io/part-of: morpheus-operator
    app.kubernetes.io/managed-by: kustomize
  name: morpheus-viewer-role
rules:
- apiGroups:
  - ai.redhat.com
  resources:
  - morpheuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai.redhat.com
  resources:
  - morpheuses/status
  verbs:
  - get
