apiVersion: ai.redhat.com/v1alpha1
kind: Morpheus
metadata:
  labels:
    app.kubernetes.io/name: morpheus
    app.kubernetes.io/instance: morpheus-sample
    app.kubernetes.io/part-of: morpheus-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: morpheus-operator
  name: morpheus-example
spec:
  serviceAccountName: morpheus-sa
  autoBindSccToSa: true
  milvus:
    minio:
      rootUser: admin
      rootPassword: admin123#
  jupyter:
    labPassword: yourPassword
    environmentVars:
#      Will be created in configmap as OPENAI_API_KEY
      openaiApiKey: your-api-key-value-goes-here
#      Will be created in configmap as YOUR_ENV_VARIABLE_HERE
      yourEnvVariableHere: your-env-var-value-goes-here-again
#      This is also supported
      MY_ENV_VAR_KEY: my-env-var-val


